/**
 * Validation Rules Constants
 */

export const VALIDATION_RULES = {
  // Password
  PASSWORD_MIN_LENGTH: 8,
  PASSWORD_MAX_LENGTH: 128,

  // Username
  USERNAME_MIN_LENGTH: 3,
  USERNAME_MAX_LENGTH: 50,

  // Names
  NAME_MIN_LENGTH: 2,
  NAME_MAX_LENGTH: 100,

  // Exercise
  EXERCISE_NAME_MIN_LENGTH: 2,
  EXERCISE_NAME_MAX_LENGTH: 100,
  EXERCISE_DESCRIPTION_MAX_LENGTH: 500,

  // Plan
  PLAN_NAME_MIN_LENGTH: 2,
  PLAN_NAME_MAX_LENGTH: 100,
  PLAN_DESCRIPTION_MAX_LENGTH: 1000,
  PLAN_MIN_WEEKS: 1,
  PLAN_MAX_WEEKS: 52,
  PLAN_MIN_WORKOUTS_PER_WEEK: 1,
  PLAN_MAX_WORKOUTS_PER_WEEK: 7,

  // Cycle
  CYCLE_NAME_MIN_LENGTH: 2,
  CYCLE_NAME_MAX_LENGTH: 100,
  CYCLE_DESCRIPTION_MAX_LENGTH: 1000,

  // Workout
  WORKOUT_NAME_MIN_LENGTH: 2,
  WORKOUT_NAME_MAX_LENGTH: 100,
  WORKOUT_NOTES_MAX_LENGTH: 1000,

  // Sets
  MIN_REPS: 1,
  MAX_REPS: 999,
  MIN_WEIGHT: 0,
  MAX_WEIGHT: 999999,
  MIN_DURATION: 0,
  MAX_DURATION: 86400, // 24 hours in seconds
  MIN_DISTANCE: 0,
  MAX_DISTANCE: 999999,
  MIN_RPE: 1,
  MAX_RPE: 10,

  // Metrics
  METRIC_NAME_MIN_LENGTH: 2,
  METRIC_NAME_MAX_LENGTH: 100,
  METRIC_NOTES_MAX_LENGTH: 500,
} as const;

